"""Create chats and chat_members tablesnewVeersion

Revision ID: df2a85dde8d8
Revises: 09367485313c
Create Date: 2025-11-27 15:06:30.671225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2a85dde8d8'
down_revision: Union[str, Sequence[str], None] = '09367485313c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('device_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_chat_members_device_id'), 'chat_members', ['device_id'], unique=False)
    op.add_column('users', sa.Column('device_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_column('users', 'device_id')
    op.drop_index(op.f('ix_chat_members_device_id'), table_name='chat_members')
    op.drop_column('chat_members', 'device_id')
    # ### end Alembic commands ###
